[package]
name = "charj"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/phodal/charj"
documentation = "https://github.com/phodal/charj"
homepage = "https://github.com/phodal/charj"
description = """
Charj is a language for describe other languages
"""
categories = ["text-processing", "command-line-interface", "development-tools", "parser-implementations", "parsing"]
exclude = [
    "benchmark/*",
    "fixtures/*",
    ".github/*",
    ".gitattributes",
    ".adr.json",
    ".cargo_vcs_info.json",
]

[dependencies]


[workspace]
members = [
    "parser",
    "compiler"
]
