[package]
name = "compiler"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.1.0-llvm10sample", features = ["target-webassembly", "target-bpf", "llvm10-0"] }

[dev-dependencies]
#solana_rbpf = "=0.1.32"