name: Charj Build

on: [push]

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    container: hyperledgerlabs/solang:ci
    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test --all
