name: Charj Build

on: [push]

jobs:
# we know how to build a llvm with llvmenv in Ubuntu or macOS server, but it's slowly. So I just copy the solang config
# But as a open source project, we shouldn't to use others server.

  linux:
    name: Linux
    runs-on: ubuntu-18.04
    container: hyperledgerlabs/solang:ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust stable
        run: rustup default stable
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release

  mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download LLVM
        run: curl -sS -o llvm10.0-mac.tar.gz https://solang.io/download/llvm10.0-mac.tar.gz
      - name: Extract LLVM
        run: tar zxf llvm10.0-mac.tar.gz
      - name: Add LLVM to Path
        run: echo "$(pwd)/llvm10.0/bin" >> $GITHUB_PATH
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release


  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download LLVM
        run: curl -sS -o c:\llvm.zip https://solang.io/download/llvm10.0.zip
      - name: Extract LLVM
        run: unzip c:\llvm.zip -d c:/
      - name: Add LLVM to Path
        run: echo "c:\llvm10.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
